# This workflow runs every morning at midnight. It will run cargo hack
# and a build with msrv. If any dependency breaks our crate, we will
# know ASAP.
#
# - hack: check combinations of feature flags
# - msrv: check that the msrv specified in the crate is correct
permissions:
  contents: read

on:
  schedule:
    - cron: '0 0 * * *'

name: rolling
jobs:

  hack:
    # cargo-hack checks combinations of feature flags to ensure that features are all additive
    # which is required for feature unification
    runs-on: ubuntu-latest
    name: ubuntu / rolling / features
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install stable
        uses: dtolnay/rust-toolchain@stable

      - name: cargo install cargo-hack
        uses: taiki-e/install-action@cargo-hack

      # intentionally no target specifier; see https://github.com/jonhoo/rust-ci-conf/pull/4
      # --feature-powerset runs for every combination of features
      - name: cargo hack
        run: |
          cargo update
          cargo hack --feature-powerset check

  msrv:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        msrv: ["1.80"]
    name: ubuntu / ${{ matrix.msrv }} (${{ matrix.commit }})
    steps:

      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install ${{ matrix.msrv }}
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.msrv }}

      - name: cargo +${{ matrix.msrv }} check
        run: |
          cargo update
          cargo check --all-features
